### ISSUE TITLE
Landscape photography camera, shows there is a problem.

### ISSUE THREAD

**Issue by guolidaxian** [weta-vn/freemar_image_picker#1]
1, first of all, feel you provided very much so good open source products, like it very much. It's very useful. I are preparing to start a business, such as just need such a small tool, such as entrepreneurial success, I will come back to support you, thank you for your efforts.
2. Problem description: when come across your mobile phone, camera shows that there is a problem
3, advice: if can have skin care function, the effect is better, filter suggested a few more

**Comment by weta-vn** [comment]
Thanks @guolidaxian for your great feedback, we are very glad to hear that you like our products.
We will definitely think about adding more filters in the next versions.
About camera problem, can you give us more detailed information. What do "come across your mobile phone" means ? We don't really understand that.

**Comment by guolidaxian** [comment]
> Thanks @guolidaxian for your great feedback, we are very glad to hear that you like our product.
> We will definitely think about adding more filters in the next versions.
> About camera problem, can you give us more detailed information. What do "come across your mobile phone" means ? We don't really understand that.



> 感谢@guolidaxian的反馈，我们很高兴听到您喜欢我们的产品。
> 我们肯定会考虑在下一个版本中添加更多过滤器。
> 关于相机问题，你能给我们更详细的信息吗？“遇到你的手机”是什么意思？我们真的不明白。




> Thanks @guolidaxian for your great feedback, we are very glad to hear that you like our product.
> We will definitely think about adding more filters in the next versions.
> About camera problem, can you give us more detailed information. What do "come across your mobile phone" means ? We don't really understand that.

When taking pictures with the horizontal screen of the mobile phone, the camera picture you see is inclined. I use Huawei mobile phone. Thank you very much for your efforts.

**Comment by weta-vn** [comment]
Thanks @guolidaxian 
We're working by locking screen orientiation in portrait mode when using image picker function.
This improvement will be release in next version.

**Comment by weta-vn** [comment]
@guolidaxian we fixed this problem at v0.0.2.
https://pub.dev/packages/advance_image_picker
Please confirm that.

Thank you very much.

**Comment by machadoguilhermebr** [comment]
I really liked your plugin, but this problem still exists

https://user-images.githubusercontent.com/67190749/124056677-8b7ad100-d9fc-11eb-8c98-1b6472fed381.mp4

**Comment by machadoguilhermebr** [comment]
https://user-images.githubusercontent.com/67190749/124056934-0217ce80-d9fd-11eb-874c-8184527434f5.mp4

**Comment by weta-vn** [comment]
>  WhatsApp.Video.2021-06-30.at.23.42.03.mp4

@machadoguilhermebr Thank you for your feedback. We'll check & fix it asap!

**Comment by machadoguilhermebr** [comment]
first, thank you for the effort to improve this amazing plugin.

I noticed that the CameraPreview has been fixed

but all images are now saved as portrait, even taking the photo as landscape

follow an example photo



follow photo taken with cell phone in landscape

![CAP4863852803273383407](https://user-images.githubusercontent.com/67190749/124321028-59c84e00-db53-11eb-847d-993adc6ffa22.jpg)

**Comment by weta-vn** [comment]
@machadoguilhermebr we're sorry about late reply.
We'll confirm & plan to improve this issue in the next release.

**Comment by guolidaxian** [comment]
> @guolidaxian我们在 v0.0.2 修复了这个问题。
> https://pub.dev/packages/advance_image_picker
> 请确认。
> 
> 非常感谢你。

That's great, problem has been solved, thank you for your efforts and pay!
